name: Build Windows App (MSBuild)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # 수동 실행을 위한 트리거

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      # 워크디렉토리에 있는 iron.sln 파일을 Release 구성 및 x64 플랫폼으로 빌드
      run: msbuild iron.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      # 빌드된 iRon.exe 파일을 다운로드할 수 있도록 아티팩트로 업로드
      uses: actions/upload-artifact@v4
      with:
        name: iRon-Advanced-Release
        path: x64/Release/iRon.exe
